services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - tidb_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - tidb_net

  kafka-consumer:
    build:
      context: ./backend
      dockerfile: Dockerfile.consumer
    container_name: kafka-consumer
    depends_on:
      - kafka
    networks:
      - tidb_net

  tidb:
    image: pingcap/tidb:latest
    container_name: tidb-server
    ports:
      - "4000:4000"
    volumes:
      - tidb-data:/var/lib/tidb
    networks:
          - tidb_net
          

  backend:
    build:
      ./backend
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
     - tidb
    networks:
       - tidb_net

  frontend:
    build:
      ./frontend
    container_name: web-client
    ports:
       - "8080:80"
    networks:
     - tidb_net

networks:
  tidb_net:
    driver: bridge

volumes:
  tidb-data: